# Generated by Django 3.2.18 on 2023-05-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20230514_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Description',
        ),
    ]
