# Generated by Django 3.2.18 on 2023-07-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20230516_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='caption',
            field=models.CharField(default='Image ofListing ', max_length=65),
        ),
    ]
